// GENERATED by `bun run --cwd vsworker plugins generate` — edit vsworker/plugins.jsonc instead.
// Star imports are deliberate: they capture both ESM and CJS namespaces uniformly, which the runtime
// then normalizes in src/bundle.ts.
import type { Raw } from "./bundle"
import * as m0 from "../plugins/hello/index.ts"

export const server: readonly Raw[] = [
  {
    id: "hello",
    source: "local",
    spec: "vsworker/plugins/hello/index.ts",
    pkg: { name: "hello", version: "0.0.0" },
    options: undefined,
    defaultEnabled: false,
    mod: m0,
  },
]
