// GENERATED by `bun run --cwd vsworker bundle generate` — edit vsworker/bundle.jsonc instead.
// Star imports are deliberate: they capture both ESM and CJS namespaces uniformly, which the runtime
// then normalizes in src/plugins.ts.
import type { Raw } from "./plugins"
import * as m0 from "../plugins/hello/index.ts"

export const server: readonly Raw[] = [
  {
    id: "hello",
    source: "local",
    spec: "vsworker/plugins/hello/index.ts",
    pkg: { name: "hello", version: "0.0.0" },
    options: undefined,
    defaultEnabled: false,
    description: "Template and smoke test for the bundling pipeline. Off by default.",
    mod: m0,
  },
]
