// GENERATED by `bun run --cwd vsworker bundle generate` — edit vsworker/bundle.jsonc instead.
// Skill files are inlined rather than imported as assets so the same module works under `bun dev`, inside the
// compiled binary, and inside the Node desktop bundle. The runtime writes them to the cache dir on first use.
import type { Raw } from "./skills"

export const hash = "54780c26bc6a16d1689e07823af1367aa1b30c6335ce5d8a8d89b426d2538ac2"

export const skills: readonly Raw[] = [
  {
    id: "hello",
    defaultEnabled: false,
    description: "Template and smoke test for skill bundling. Off by default.",
    files: [
      {
        path: "SKILL.md",
        encoding: "utf8",
        executable: false,
        data: "---\nname: hello\ndescription: Template and smoke test for the VsWorker skill bundling pipeline. Use only when someone explicitly asks to verify that bundled skills reach the model.\n---\n\n# Bundled skill template\n\nThis skill ships inside every VsWorker build and is off by default, so a release is unaffected until someone\nturns it on with `opencode vsworker skills enable hello`. It exists to prove the pipeline end to end: the file\nyou are reading was compiled into the binary, written to the cache directory at startup, and handed to you by\nthe `skill` tool.\n\nCopy `vsworker/skills/hello/` as the starting point for a real in-house skill, or run\n`bun run --cwd vsworker bundle import skill <name>` to vendor one you already keep in your global skills\ndirectory. Read `vsworker/README.md` for the field reference.\n\n## What to do when this skill loads\n\nSay that the bundled skill pipeline works, and report the base directory printed above the file list. Nothing\nelse. This skill carries no instructions for real work.\n",
      },
    ],
  },
]
