// GENERATED by `bun run --cwd vsworker plugins generate` — edit vsworker/plugins.jsonc instead.
// Star imports are deliberate: they capture both ESM and CJS namespaces uniformly, which the runtime
// then normalizes in src/bundle.ts.
import type { Raw } from "./bundle"

export const tui: readonly Raw[] = []
