// GENERATED by `bun run --cwd vsworker bundle generate` — edit vsworker/bundle.jsonc instead.
// Star imports are deliberate: they capture both ESM and CJS namespaces uniformly, which the runtime
// then normalizes in src/plugins.ts.
import type { Raw } from "./plugins"

export const tui: readonly Raw[] = []
